# Generated by Django 4.0.5 on 2022-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=7)),
                ('Name', models.CharField(max_length=50)),
                ('complaint_txt', models.CharField(max_length=3000)),
            ],
        ),
    ]
