# Generated by Django 4.0.5 on 2022-07-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='department',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_txt',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='id_number',
            field=models.CharField(max_length=9),
        ),
    ]
