# Generated by Django 4.0.5 on 2022-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0002_complaints_department_alter_complaints_complaint_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='department',
            field=models.CharField(default='hai', max_length=30),
        ),
    ]
