# Generated by Django 4.0.5 on 2022-07-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0003_alter_complaints_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='department',
            field=models.CharField(max_length=30),
        ),
    ]
