# Generated by Django 4.0.5 on 2022-07-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0005_complaints_videoproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='imageproof',
            field=models.ImageField(blank='True', null=True, upload_to='images/'),
        ),
    ]
