# Generated by Django 4.0.5 on 2022-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0007_complaints_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='seen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
