# Generated by Django 4.0.5 on 2022-08-06 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0008_complaints_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
