# Generated by Django 4.0.5 on 2022-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0009_complaints_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
