# Generated by Django 4.0.5 on 2022-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0010_alter_complaints_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solveddatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=9)),
                ('Name', models.CharField(max_length=50)),
                ('complaint_txt', models.CharField(max_length=4000)),
                ('Class', models.CharField(blank=True, max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=30)),
                ('videoproof', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('imageproof', models.ImageField(blank='True', null=True, upload_to='images/')),
            ],
        ),
    ]
