# Generated by Django 4.0.5 on 2022-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_Management_System', '0011_solveddatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solveddatabase',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
